# Generated by Django 5.0.4 on 2024-05-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuID', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('BirthDate', models.DateField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
