# Generated by Django 5.0.4 on 2024-05-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RID', models.AutoField(primary_key=True, serialize=False)),
                ('RName', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='RID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.role'),
            preserve_default=False,
        ),
    ]
